=== troilus/toyota/manual/ewd/dtd/txt-search.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.3  UPDATE Aug. 24, 2012    -->
<!ELEMENT tmc-service-txt-search (pub+)>
<!ELEMENT pub (servcat+)>
<!ATTLIST pub
	id ID #REQUIRED
	type (RM | NM | EM) #REQUIRED
>
<!ELEMENT servcat (section+)>
<!ATTLIST servcat
	id CDATA #REQUIRED
	t CDATA #REQUIRED
>
<!ELEMENT section (ttl+)>
<!ATTLIST section
	id ID #REQUIRED
	t CDATA #REQUIRED
>
<!ELEMENT ttl (ncf-para+ | (emlink?, para*))>
<!ATTLIST ttl
	id ID #REQUIRED
	t CDATA #REQUIRED
	term-id-from CDATA #IMPLIED
>
<!ELEMENT ncf-para (para)>
<!ATTLIST ncf-para
	ncf-para-category CDATA #REQUIRED
	t CDATA #REQUIRED
>
<!ELEMENT emlink EMPTY>
<!ATTLIST emlink
	type CDATA #REQUIRED
	code CDATA #REQUIRED
>
<!ELEMENT para ((name+, (p*, parts+)?) | (emlink, name, parts))>
<!ATTLIST para
	category CDATA #REQUIRED
	id ID #REQUIRED
	term-id-from CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>
<!ELEMENT p EMPTY>
<!ATTLIST p
	id ID #REQUIRED
	t CDATA #REQUIRED
>
<!ELEMENT parts EMPTY>
<!ATTLIST parts
	parts-id CDATA #REQUIRED
	t CDATA #REQUIRED
>

=== troilus/toyota/manual/ewd/difference/txt-search.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tmc-service-txt-search SYSTEM "./dtd/txt-search.dtd">
<tmc-service-txt-search>
  <pub id="EM3140CG" type="EM">
    <servcat id="_IT" t="概述">
      <section id="_INTRO" t="-">
        <ttl id="_INTRO01" t="概述" term-id-from="001">
          <emlink type="-" code="ewd_type=intro;ewd=INTRO01"/>
        </ttl>
        <ttl id="_INTRO02" t="缩略语" term-id-from="001">
          <emlink type="-" code="ewd_type=intro;ewd=INTRO02"/>
        </ttl>
        <ttl id="_INTRO03" t="术语和符号表" term-id-from="001">
          <emlink type="-" code="ewd_type=intro;ewd=INTRO03"/>
        </ttl>
        <ttl id="_INTRO04" t="线束维修概述" term-id-from="001">
          <emlink type="-" code="ewd_type=intro;ewd=INTRO04"/>
        </ttl>
        <ttl id="_INTRO05" t="端子和连接器维修" term-id-from="001">
          <emlink type="-" code="ewd_type=intro;ewd=INTRO05"/>
        </ttl>
      </section>
    </servcat>
    <servcat id="_SY" t="系统电路">
      <section id="_EG" t="发动机/混合动力系统">
        <ttl id="_SYS019" t="冷却风扇（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS019"/>
        </ttl>
        <ttl id="_SYS020" t="冷却风扇（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS020"/>
        </ttl>
        <ttl id="_SYS021" t="巡航控制（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS021"/>
        </ttl>
        <ttl id="_SYS022" t="巡航控制（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS022"/>
        </ttl>
        <ttl id="_SYS023" t="发动机控制（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS023"/>
        </ttl>
        <ttl id="_SYS024" t="发动机控制（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS024"/>
        </ttl>
        <ttl id="_SYS025" t="点火（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS025"/>
        </ttl>
        <ttl id="_SYS026" t="点火（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS026"/>
        </ttl>
        <ttl id="_SYS027" t="起动（带智能进入和起动系统）（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS027"/>
        </ttl>
        <ttl id="_SYS028" t="起动（带智能进入和起动系统）（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS028"/>
        </ttl>
        <ttl id="_SYS029" t="起动（不带智能进入和起动系统）（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS029"/>
        </ttl>
        <ttl id="_SYS030" t="起动（不带智能进入和起动系统）（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS030"/>
        </ttl>
      </section>
      <section id="_DR" t="动力传动系">
        <ttl id="_SYS015" t="CVT 和换档指示灯（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS015"/>
        </ttl>
        <ttl id="_SYS016" t="CVT 和换档指示灯（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS016"/>
        </ttl>
        <ttl id="_SYS017" t="换档锁止（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS017"/>
        </ttl>
        <ttl id="_SYS018" t="换档锁止（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS018"/>
        </ttl>
      </section>
      <section id="_BK" t="制动">
        <ttl id="_SYS009" t="ABS（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS009"/>
        </ttl>
        <ttl id="_SYS010" t="ABS（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS010"/>
        </ttl>
        <ttl id="_SYS011" t="TRC（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS011"/>
        </ttl>
        <ttl id="_SYS012" t="TRC（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS012"/>
        </ttl>
        <ttl id="_SYS013" t="VSC（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS013"/>
        </ttl>
        <ttl id="_SYS014" t="VSC（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS014"/>
        </ttl>
      </section>
      <section id="_ST" t="转向">
        <ttl id="_SYS117" t="EPS (1ZR-FE)（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS117"/>
        </ttl>
        <ttl id="_SYS118" t="EPS (2ZR-FE)（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS118"/>
        </ttl>
        <ttl id="_SYS119" t="EPS (4ZR-FE)（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS119"/>
        </ttl>
        <ttl id="_SYS120" t="EPS (7ZR-FE)（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS120"/>
        </ttl>
        <ttl id="_SYS121" t="转向锁止（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS121"/>
        </ttl>
        <ttl id="_SYS122" t="转向锁止（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS122"/>
        </ttl>
      </section>
      <section id="_AV" t="音频/视频/车载通信系统">
        <ttl id="_SYS001" t="音响系统（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS001"/>
        </ttl>
        <ttl id="_SYS002" t="音响系统（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS002"/>
        </ttl>
        <ttl id="_SYS003" t="导航系统（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS003"/>
        </ttl>
        <ttl id="_SYS004" t="导航系统（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS004"/>
        </ttl>
        <ttl id="_SYS005" t="后视野监视系统（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS005"/>
        </ttl>
        <ttl id="_SYS006" t="后视野监视系统（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS006"/>
        </ttl>
        <ttl id="_SYS007" t="丰田驻车辅助传感器系统（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS007"/>
        </ttl>
        <ttl id="_SYS008" t="丰田驻车辅助传感器系统（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS008"/>
        </ttl>
      </section>
      <section id="_PS" t="电源/网络">
        <ttl id="_SYS109" t="充电（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS109"/>
        </ttl>
        <ttl id="_SYS110" t="充电（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS110"/>
        </ttl>
        <ttl id="_SYS111" t="DLC3（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS111"/>
        </ttl>
        <ttl id="_SYS112" t="DLC3（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS112"/>
        </ttl>
        <ttl id="_SYS113" t="多路通信系统 (CAN)（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS113"/>
        </ttl>
        <ttl id="_SYS114" t="多路通信系统 (CAN)（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS114"/>
        </ttl>
        <ttl id="_SYS115" t="电源（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS115"/>
        </ttl>
        <ttl id="_SYS116" t="电源（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS116"/>
        </ttl>
        <ttl id="_SYS123" t="接地点（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS123"/>
        </ttl>
        <ttl id="_SYS124" t="接地点（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS124"/>
        </ttl>
      </section>
      <section id="_IN" t="车辆内饰">
        <ttl id="_SYS067" t="自动空调（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS067"/>
        </ttl>
        <ttl id="_SYS068" t="自动空调（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS068"/>
        </ttl>
        <ttl id="_SYS069" t="点烟器（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS069"/>
        </ttl>
        <ttl id="_SYS070" t="点烟器（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS070"/>
        </ttl>
        <ttl id="_SYS071" t="时钟（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS071"/>
        </ttl>
        <ttl id="_SYS072" t="时钟（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS072"/>
        </ttl>
        <ttl id="_SYS073" t="组合仪表（带 TFT 显示屏）（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS073"/>
        </ttl>
        <ttl id="_SYS074" t="组合仪表（带 TFT 显示屏）（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS074"/>
        </ttl>
        <ttl id="_SYS075" t="组合仪表（不带 TFT 显示屏）（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS075"/>
        </ttl>
        <ttl id="_SYS076" t="组合仪表（不带 TFT 显示屏）（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS076"/>
        </ttl>
        <ttl id="_SYS077" t="门锁控制（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS077"/>
        </ttl>
        <ttl id="_SYS078" t="门锁控制（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS078"/>
        </ttl>
        <ttl id="_SYS079" t="照明（GTMC 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS079"/>
        </ttl>
        <ttl id="_SYS080" t="照明（TFTM 制造）" term-id-from="001">
          <emlink type="-" code="ewd_type=system;ewd=SYS080"/>
        </ttl>
