=== troilus/toyota/manual/pub_sys/dtd/sakuin-index.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- #  DTD VERSION 1.5  UPDATE May. 22, 2013    -->
<!ELEMENT tmc-service-sakuin-index (pub)>
<!ELEMENT pub (index+)>
<!ATTLIST pub
	id ID #REQUIRED
>
<!ELEMENT index (parts+)>
<!ATTLIST index
	label CDATA #REQUIRED
>
<!ELEMENT parts (name)>
<!ATTLIST parts
	parts-id CDATA #REQUIRED
	p-type CDATA #REQUIRED
>
<!ELEMENT name (#PCDATA)>

=== troilus/toyota/manual/pub_sys/sakuin-index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE tmc-service-sakuin-index SYSTEM "./dtd/sakuin-index.dtd">
<tmc-service-sakuin-index>
<pub id="RM3140CG">
<index label="1">
<parts p-type="1" parts-id="35068E">
<name>一档和倒档制动器回位弹簧分总成</name>
</parts>
<parts p-type="2" parts-id="B300014">
<name>一档从动齿轮径向间隙</name>
</parts>
<parts p-type="2" parts-id="B300008">
<name>一档从动齿轮轴向间隙</name>
</parts>
<parts p-type="1" parts-id="33335">
<name>一档齿轮</name>
</parts>
<parts p-type="1" parts-id="33345">
<name>一档齿轮衬套</name>
</parts>
<parts p-type="1" parts-id="33335C">
<name>一档齿轮滚针轴承</name>
</parts>
<parts p-type="1" parts-id="33348">
<name>一档齿轮止推垫圈</name>
</parts>
<parts p-type="1" parts-id="33348A">
<name>一档齿轮止推垫圈销或钢球</name>
</parts>
</index>
<index label="2">
<parts p-type="2" parts-id="B300015">
<name>二档从动齿轮径向间隙</name>
</parts>
<parts p-type="2" parts-id="B300009">
<name>二档从动齿轮轴向间隙</name>
</parts>
<parts p-type="1" parts-id="33332">
<name>二档齿轮</name>
</parts>
<parts p-type="1" parts-id="33356A">
<name>二档齿轮轴承内座圈</name>
</parts>
<parts p-type="1" parts-id="33332B">
<name>二档齿轮滚针轴承</name>
</parts>
<parts p-type="1" parts-id="33381">
<name>二档同步器外锁环</name>
</parts>
</index>
<index label="3">
<parts p-type="1" parts-id="33423A">
<name>三档从动齿轮</name>
</parts>
<parts p-type="2" parts-id="B300016">
<name>三档从动齿轮径向间隙</name>
</parts>
<parts p-type="2" parts-id="B300010">
<name>三档从动齿轮轴向间隙</name>
</parts>
<parts p-type="1" parts-id="33333">
<name>三档齿轮</name>
</parts>
<parts p-type="1" parts-id="33333A">
<name>三档齿轮滚针轴承</name>
</parts>
<parts p-type="1" parts-id="33368G">
<name>三档齿轮同步器锁环</name>
</parts>
</index>
<index label="4">
<parts p-type="1" parts-id="33422B">
<name>四档从动齿轮</name>
</parts>
<parts p-type="2" parts-id="B300017">
<name>四档从动齿轮径向间隙</name>
</parts>
<parts p-type="2" parts-id="F0001ZM">
<name>四档从动齿轮轴向间隙</name>
</parts>
<parts p-type="1" parts-id="33334">
<name>四档齿轮</name>
</parts>
<parts p-type="1" parts-id="33334B">
<name>四档齿轮轴承隔垫</name>
</parts>
<parts p-type="1" parts-id="33334A">
<name>四档齿轮滚针轴承</name>
</parts>
<parts p-type="1" parts-id="33368H">
<name>四档齿轮同步器锁环</name>
</parts>
</index>
<index label="5">
<parts p-type="1" parts-id="33428C">
<name>五档从动齿轮</name>
</parts>
<parts p-type="2" parts-id="B300018">
<name>五档从动齿轮径向间隙</name>
</parts>
<parts p-type="2" parts-id="B300012">
<name>五档从动齿轮轴向间隙</name>
</parts>
<parts p-type="1" parts-id="33336">
<name>五档齿轮</name>
</parts>
<parts p-type="1" parts-id="33359">
<name>五档齿轮轴承内座圈</name>
</parts>
<parts p-type="1" parts-id="33359A">
<name>五档齿轮轴承内座圈锁止钢球</name>
</parts>
<parts p-type="1" parts-id="33336A">
<name>五档齿轮滚针轴承</name>
</parts>
</index>
<index label="6">
<parts p-type="1" parts-id="33429B">
<name>六档从动齿轮</name>
</parts>
<parts p-type="2" parts-id="B300019">
<name>六档从动齿轮径向间隙</name>
</parts>
<parts p-type="2" parts-id="B300013">
<name>六档从动齿轮轴向间隙</name>
</parts>
<parts p-type="1" parts-id="3335AA">
<name>六档齿轮轴承钢球内座圈齿条 (MTM)</name>
</parts>
<parts p-type="1" parts-id="3335A">
<name>六档齿轮轴承内座圈 (MTM)</name>
</parts>
<parts p-type="1" parts-id="33337A">
<name>六档齿轮滚针轴承</name>
</parts>
<parts p-type="1" parts-id="33337">
<name>六档齿轮分总成</name>
</parts>
</index>
<index label="A">
<parts p-type="2" parts-id="F0001AM">
<name>A</name>
</parts>
<parts p-type="2" parts-id="B190987">
<name>ACC CUT 继电器</name>
</parts>
<parts p-type="2" parts-id="B001900">
<name>加速踏板</name>
</parts>
<parts p-type="1" parts-id="78110K">
<name>加速踏板传感器总成</name>
</parts>
<parts p-type="1" parts-id="31483B">
<name>蓄压器至挠性软管的管</name>
</parts>
<parts p-type="3" parts-id="ZZZZZZ">
<name>主动测试  主动测试</name>
</parts>
<parts p-type="2" parts-id="B000002">
<name>执行器</name>
</parts>
<parts p-type="2" parts-id="B980074">
<name>加注制动液</name>
</parts>
<parts p-type="2" parts-id="B400556">
<name>调节螺母</name>
</parts>
<parts p-type="2" parts-id="B000005">
<name>调节垫片</name>
</parts>
<parts p-type="2" parts-id="F0003NL">
<name>受波干扰影响</name>
</parts>
<parts p-type="1" parts-id="89170A">
<name>气囊 ECU 总成</name>
</parts>
<parts p-type="1" parts-id="89174A">
<name>左前空气囊传感器</name>
</parts>
<parts p-type="1" parts-id="89173A">
<name>右前空气囊传感器</name>
</parts>
<parts p-type="1" parts-id="17705">
<name>空气滤清器盖分总成</name>
</parts>
<parts p-type="2" parts-id="B000007">
<name>空气滤清器壳</name>
</parts>
<parts p-type="1" parts-id="17701">
<name>空气滤清器壳分总成</name>
</parts>
<parts p-type="1" parts-id="17801">
<name>空气滤清器滤芯分总成</name>
</parts>
<parts p-type="1" parts-id="17751">
<name>1 号空气滤清器进气口</name>
</parts>
<parts p-type="2" parts-id="B800043">
<name>空调装置总成</name>
</parts>
<parts p-type="2" parts-id="F00003Y">
<name>空调系统</name>
</parts>
<parts p-type="2" parts-id="B909587">
<name>空调放大器</name>
</parts>
<parts p-type="1" parts-id="88650N">
<name>空调放大器总成</name>
</parts>
<parts p-type="1" parts-id="55900">
<name>空调控制总成</name>
</parts>
<parts p-type="2" parts-id="F0000IS">
<name>空调滤清器</name>
</parts>
<parts p-type="1" parts-id="82210K">
<name>空调线束总成</name>
</parts>
<parts p-type="2" parts-id="F0003W3">
<name>空调面板</name>
</parts>
<parts p-type="2" parts-id="B559200">
<name>空调面板总成</name>
</parts>
<parts p-type="2" parts-id="F000158">
<name>空调压力传感器</name>
</parts>
<parts p-type="1" parts-id="87050">
<name>空调散热器总成</name>
</parts>
<parts p-type="2" parts-id="M000112">
<name>空调系统</name>
</parts>
<parts p-type="2" parts-id="F0003VX">
<name>空调装置</name>
</parts>
<parts p-type="1" parts-id="87212">
<name>1 号后风管</name>
</parts>
<parts p-type="1" parts-id="87201B">
<name>2 号风管分总成</name>
</parts>
<parts p-type="1" parts-id="87201F">
<name>3 号风管分总成</name>
</parts>
<parts p-type="1" parts-id="88548B">
<name>空气滤清器壳</name>
</parts>
<parts p-type="1" parts-id="89467B">
<name>空燃比传感器</name>
</parts>
<parts p-type="2" parts-id="B894653">
<name>空燃比传感器</name>
</parts>
<parts p-type="2" parts-id="B894670">
<name>空燃比传感器</name>
</parts>
<parts p-type="2" parts-id="B400029">
<name>空气泄漏</name>
</parts>
<parts p-type="2" parts-id="B004004">
<name>气密性</name>
</parts>
<parts p-type="1" parts-id="17361M">
<name>空气管</name>
</parts>
<parts p-type="1" parts-id="88719A">
<name>空调压力传感器</name>
</parts>
<parts p-type="1" parts-id="88710">
<name>空调管总成</name>
</parts>
<parts p-type="1" parts-id="55909C">
<name>空气混合风门控制拉索分总成</name>
</parts>
<parts p-type="1" parts-id="87106H">
<name>空气混合风门伺服机构分总成</name>
</parts>
<parts p-type="2" parts-id="B800648">
<name>环境温度传感器</name>
</parts>
<parts p-type="2" parts-id="F0000C4">
<name>放大器天线</name>
</parts>
<parts p-type="1" parts-id="86300B">
<name>1 号放大器天线总成</name>
</parts>
<parts p-type="1" parts-id="86101">
<name>天线芯线分总成</name>
</parts>
<parts p-type="2" parts-id="B801004">
<name>天线型</name>
</parts>
<parts p-type="1" parts-id="04945">
<name>前消音垫片组件</name>
</parts>
<parts p-type="2" parts-id="B400613">
<name>后消音垫片组件</name>
</parts>
<parts p-type="2" parts-id="B980194">
<name>输出任何其他 DTC</name>
</parts>
<parts p-type="1" parts-id="88897P">
<name>吸气器</name>
</parts>
<parts p-type="1" parts-id="74630E">
<name>左后辅助拉手总成</name>
</parts>
<parts p-type="1" parts-id="74620C">
<name>右后辅助拉手总成</name>
</parts>
<parts p-type="1" parts-id="74610A">
<name>辅助拉手分总成</name>
</parts>
<parts p-type="2" parts-id="F000295">
<name>助力图写入</name>
</parts>
<parts p-type="2" parts-id="D12040Z">
<name>音频/视频系统</name>
</parts>
<parts p-type="2" parts-id="M000180">
<name>音频和视频系统</name>
</parts>
<parts p-type="2" parts-id="F0001V7">
<name>音响设定</name>
</parts>
<parts p-type="2" parts-id="B002955">
<name>Auto LSD Switch</name>
</parts>
<parts p-type="1" parts-id="89120A">
<name>自动灯光控制传感器</name>
</parts>
<parts p-type="2" parts-id="F0003ZD">
<name>自动灯光控制传感器</name>
</parts>
<parts p-type="2" parts-id="D1002BZ">
<name>自动传动桥</name>
</parts>
<parts p-type="2" parts-id="F0000HG">
<name>自动传动桥“驻车”机构</name>
</parts>
<parts p-type="2" parts-id="F000018">
<name>车桥系统</name>
</parts>
</index>
<index label="B">
<parts p-type="2" parts-id="F00015G">
<name>背门门控灯开关</name>
</parts>
<parts p-type="1" parts-id="84490A">
<name>后声纳或侦测声纳开关总成</name>
</parts>
<parts p-type="1" parts-id="81550N">
<name>倒车灯灯泡</name>
</parts>
<parts p-type="1" parts-id="64811">
<name>背窗玻璃</name>
</parts>
<parts p-type="2" parts-id="F0000CR">
<name>背窗玻璃</name>
</parts>
<parts p-type="1" parts-id="64813D">
<name>背窗玻璃粘合剂密封条</name>
</parts>
<parts p-type="2" parts-id="B681018">
<name>背窗玻璃隔垫</name>
</parts>
<parts p-type="1" parts-id="56115B">
<name>背窗玻璃 1 号挡块</name>
</parts>
<parts p-type="1" parts-id="56116D">
<name>背窗玻璃 2 号挡块</name>
</parts>
<parts p-type="1" parts-id="84210">
<name>倒车灯开关总成</name>
</parts>
<parts p-type="2" parts-id="B009032">
<name>倒车灯开关</name>
</parts>
<parts p-type="2" parts-id="F0000IO">
<name>球节和防尘罩</name>
</parts>
<parts p-type="2" parts-id="B980030">
<name>基本功能</name>
</parts>
<parts p-type="2" parts-id="A288000">
<name>蓄电池</name>
</parts>
<parts p-type="2" parts-id="B000016">
<name>蓄电池</name>
</parts>
<parts p-type="1" parts-id="74411">
<name>蓄电池托架</name>
</parts>
<parts p-type="1" parts-id="74404A">
<name>蓄电池卡夹分总成</name>
</parts>
<parts p-type="2" parts-id="F00007A">
<name>蓄电池电流传感器</name>
</parts>
<parts p-type="1" parts-id="28850">
<name>蓄电池电流传感器总成</name>
</parts>
<parts p-type="2" parts-id="B000017">
<name>蓄电池电解液液位</name>
</parts>
<parts p-type="1" parts-id="28800J">
<name>蓄电池负极端子</name>
</parts>
<parts p-type="2" parts-id="B001850">
<name>蓄电池端子</name>
</parts>
<parts p-type="2" parts-id="F0001SI">
<name>蓄电池电压</name>
</parts>
<parts p-type="1" parts-id="33326">
<name>轴承锁止板</name>
</parts>
<parts p-type="2" parts-id="B300040">
<name>轴承位置</name>
</parts>
<parts p-type="1" parts-id="33151D">
<name>后轴承护圈 (MTM)</name>
</parts>
<parts p-type="2" parts-id="F0002PF">
<name>向传动桥加注油液前</name>
</parts>
<parts p-type="1" parts-id="71077B">
<name>长条式后排座椅座背护面</name>
</parts>
<parts p-type="1" parts-id="71075B">
<name>长条式后排座椅座垫护面</name>
</parts>
<parts p-type="2" parts-id="F00040X">
<name>遮光胶带</name>
</parts>
<parts p-type="1" parts-id="75922M">
<name>左侧 1 号遮光胶带</name>
</parts>
<parts p-type="1" parts-id="75924C">
<name>左侧 2 号遮光胶带</name>
</parts>
<parts p-type="2" parts-id="B400039">
<name>对制动管路进行放气</name>
</parts>
